using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TMP.Models
{
    public class InvoiceTransactionModel
    {
        public int InvoiceID { get; set; }
        public int InvoicePayID { get; set; }        
        public bool MstIsDeleted { get; set; }
        public bool IsCompanyErr { get; set; }
        public bool IsAttachErr { get; set; }
        public bool IsDueDateErr { get; set; }
        public bool IsTenorErr { get; set; }
        public bool IsFundReqDateErr { get; set; }
        public string TranRefNo { get; set; }
        public bool IsUpdAttach { get; set; }
        public string AttachComment { get; set; }
        public string ExporterCustomerName { get; set; }
        public Decimal TotAmt { get; set; }
            
        public DateTime DueDate { get; set; }
        public DateTime CreateDate { get; set; }        
        public DateTime ProcessDate { get; set; }
        public DateTime PaymentDate { get; set; }
        public DateTime FundReqDate { get; set; }
        public string ProgramType { get; set; }
        public string Program { get; set; }
        public int CurrencyID { get; set; }
        public string CurrencyCode { get; set; }
        public int ObligorID { get; set; }
        public int MstObligorID { get; set; }        
        public int SupplierID { get; set; }
        public int MstSupplierID { get; set; }
        public int MstBuyerID { get; set; }
        
        public int BuyerID { get; set; }
        public bool IsObligorGen { get; set; }
        public string ProcessRemark { get; set; }
        public string Status { get; set; }
        public string FunderName { get; set; }
        public int ObligorGen { get; set; }
        public string IndexStatus { get; set; }
        public string SettlementType { get; set; }
        public bool IsSupplierConf { get; set; }
        public bool IsObligorConf { get; set; }
        public bool IsFunderConf { get; set; }
        public bool IsFunderAgree { get; set; }
        public bool IsInsurance { get; set; }
        public bool IsBuyerConf { get; set; }
        public int IsSelect { get; set; }
        public int FunderID { get; set; }
        public int InsuranceID { get; set; }
        public int ServiceProviderID { get; set; }
        public int CustomerBankAccID { get; set; }
        public string FromTranDate { get; set; }
        public string ToTranDate { get; set; }
        public int CustomerID { get; set; }
        public int CustomerTypeID { get; set; }
        public bool IsUpdate { get; set; }
        public int InvoiceDetID { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public Decimal Amt { get; set; }
        public string Attach { get; set; }
        public int InvoiceAmtID { get; set; }
        public int InvoiceInsID { get; set; }
        public int InsuranceBrokerID { get; set; }
        public string PolicyNo { get; set; }
        public string InsuranceName { get; set; }
        public string InsuranceBrokerName { get; set; }
        public DateTime IssueDate { get; set; }
        public DateTime ExpDate { get; set; }
        public Decimal InsAmt { get; set; }
        public Decimal PremPer { get; set; }
        public Decimal PremAmt { get; set; }
        public string Comment { get; set; }
        public int InvoiceComID { get; set; }
        public string ComLevel { get; set; }
        public string RefNo { get; set; }
        public DateTime TranDate { get; set; }
        public Decimal ChargeAmt { get; set; }
        public string CertificateNo { get; set; }
        public Decimal QtyComm { get; set; }
        public string CommValue { get; set; }
        public string CompanyName { get; set; }
        public int InvCnt { get; set; }
        public string ObligorName { get; set; }
        public int TranCnt { get; set; }
        public Decimal TotTranAmt { get; set; }
        public Decimal TotSetAmt { get; set; }
        public Decimal TotOutStand { get; set; }
        public string ProgramTypeDesc { get; set; }
        public int Tenor { get; set; }
        public Decimal ProfMarginRate { get; set; }
        public string SupplierName { get; set; }
        public Decimal ProfitAmt { get; set; }
        public Decimal HoldbackAmt { get; set; }
        public Decimal HoldbackPer { get; set; }
        public Decimal TranFeeAmt { get; set; }
        public Decimal NetAmt { get; set; }
        public Decimal OtherFeeAmt { get; set; }       
        public Decimal FunProfitRate { get; set; }
        public Decimal FunProfitAmt { get; set; }
        public Decimal PayToSup { get; set; }
        public Decimal ProcessFee { get; set; }
        public Decimal ProfitRate { get; set; }
        public Decimal PayToiSCF { get; set; }
        public Decimal PayToExp { get; set; }
        public DateTime SetDueDate { get; set; }
        public int ExporterID { get; set; }
        public string ExporterName { get; set; }
        public string CustomerAccountNo { get; set; }
        public int PayBankID { get; set; }
        public string PayAccountNo { get; set; }
        public int PayCurrencyID { get; set; }
        public string PayProfitRefNo { get; set; }
        public DateTime PayProfitDate { get; set; }
        public string PayProcessRefNo { get; set; }        
        public DateTime PayProcessDate { get; set; }
        public Decimal PayCurrencyRate { get; set; }
        public Decimal PayProfitAmt { get; set; }
        public Decimal PayProcessFeeAmt { get; set; }
        public Decimal ProcessFeeAmt { get; set; }
        public int InvTempID { get; set; }
        public int InvTempDetID { get; set; }
        public string BuyerName { get; set; }
        public bool IsVerified { get; set; }
        public int pIsVerified { get; set; }
        public string _currentUser { get; set; }
        public string _currentStatus { get; set; }
        public decimal InsPremPer { get; set; }
        public decimal InsPremAmt { get; set; }
        public int pIsDeleted { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsGenerated { get; set; }
        public string ParentName { get; set; }
        public int SeqNo { get; set; }
        public int InsCnt { get; set; }
        
        public string Attachs { get; set; }
        public string StatusUserDesc { get; set; }
        public int CreateBy { get; set; }
        public int UpdateBy { get; set; }
        public string Remarks { get; set; }
        public DateTime ExtDueDate { get; set; }
        public int ExtTenor { get; set; }
        public int IsInsuranceVal { get; set; }
        public string SupplierCode { get; set; }
        public decimal SUPTotBalAmt { get; set; }
        public int SUPTenor { get; set; }
        public decimal SUPTotLimit { get; set; }
        public decimal SUPTotUtiAmt { get; set; }
        public decimal SUPTotSetAmt { get; set; }
        public decimal SUPTotOutStand { get; set; }
        public string ObligorCode { get; set; }
        public int OBLTenor { get; set; }
        public decimal OBLTotLimit { get; set; }
        public decimal OBLTotUtiAmt { get; set; }
        public decimal OBLTotBalAmt { get; set; }
        public decimal OBLTotSetAmt { get; set; }
        public decimal OBLTotOutStand { get; set; }
        public int NewExtTenor { get; set; }

        public string BuyerCode { get; set; }
        public int BUYTenor { get; set; }
        public decimal BUYTotLimit { get; set; }
        public decimal BUYTotUtiAmt { get; set; }
        public decimal BUYTotBalAmt { get; set; }
        public decimal BUYTotSetAmt { get; set; }
        public decimal BUYTotOutStand { get; set; }
        public string ExporterCode { get; set; }
        public string SupplierEmailID { get; set; }
        public string BuyerEmailID { get; set; }
        public string iSCFEmailID { get; set; }
        public string ObligorEmailID { get; set; }
        public string TypeDesc { get; set; }
        public string TypeStatus { get; set; }
        public DateTime PayDate { get; set; }
        public DateTime Buyer_PaidDate { get; set; }
        public Decimal Buyer_PaidAmt { get; set; }
        public string Buyer_RefNo { get; set; }
        public string Buyer_ProcessRemark { get; set; }
        public DateTime Funder_PaidDate { get; set; }
        public Decimal Funder_PaidAmt { get; set; }
        public string Funder_RefNo { get; set; }
        public string Funder_ProcessRemark { get; set; }
        public DateTime Security_PaidDate { get; set; }
        public Decimal Security_PaidAmt { get; set; }
        public string Security_RefNo { get; set; }
        public string Security_ProcessRemark { get; set; }
        public string LoginName { get; set; }
        public string ContactFullName { get; set; }
        public string ActionLevel { get; set; }
        public string Type { get; set; }
        
        public string ActionType { get; set; }        
        public int UserID { get; set; }
        public bool IsMaker { get; set; }
        public bool IsChecker { get; set; }
        public bool IsViewer { get; set; }
        public bool IsDispToCH { get; set; }
        public bool IsFoundFD { get; set; }
        public bool IsFoundID { get; set; }
        public bool IsFoundCF { get; set; }
        public bool IsDispToCD { get; set; }
        public bool IsFoundFB { get; set; }
        public bool IsFoundCC { get; set; }
        public string ProfitTypeDesc { get; set; }

        public int TotObligor { get; set; }
        public int TotSupplier { get; set; }
        public int TotFunder { get; set; }
        public int TotInsurance { get; set; }
        public bool IsAction { get; set; }
        public int ObligorBuyerID { get; set; }
        public string UploadType { get; set; }
        public bool IsNew { get; set; }
        public bool IsSupplier { get; set; }
        public int CompanyID { get; set; }
        public bool IsInsuranceCust { get; set; }
        public bool IsInvOffer { get; set; }
        public DateTime ActionDate { get; set; }
        public string ComLevelDesc { get; set; }
        public string IsSUPTranOffer { get; set; }
        public string IsSUPTransactionRequest { get; set; }
        public string IsSUPAssignmentNotice { get; set; }
        public string SUPTranOfferAttach { get; set; }
        public string SUPTransactionRequestAttach { get; set; }
        public string SUPAssignmentNoticeAttach { get; set; }
        public string IsOBLAssignmentAck { get; set; }
        public string OBLAssignmentAckAttach { get; set; }
        public string IsFUNInvOffer { get; set; }
        public string FUNInvOfferAttach { get; set; }
        public string IsFUNAssignmentNotice { get; set; }
        public string FUNAssignmentNoticeAttach { get; set; }
        public decimal RemainingAmt { get; set; }
        public decimal SettledAmt { get; set; }
    }
}